ools:
  - class_name: verl.tools.wordle_tool.WordleTool
    config:
      type: native        # local Python tool
      max_attempts: 6
    tool_schema:
      type: function      # ← add this
      function:           # ← wrap the signature inside here
        name: wordle_guess
        description: Guess a 5-letter Wordle word.
        parameters:
          type: object
          properties:
            guess:
              type: string
              description: Your 5-letter guess
          required: [guess]
