tools:
  - class_name: verl.tools.wordle_tool.WordleTool          # dotted import path
    config:
      type: native                              # local Python tool
      max_attempts: 6
      reward_shaping: true
    tool_schema:                                # OpenAI-style function signature
      name: "wordle_guess"
      description: "A tool to guess a 5-letter word in the Wordle environment."
      parameters:
        type: object
        properties:
          guess:
            type: string
            description: "Your 5-letter guess."
        required: ["guess"]
